language: java
jdk:
  - openjdk8

git:
  quiet: true

before_install:
  - sudo chmod 777 .travis/before.sh

install: true

before_script:
  - .travis/before.sh

script:
  - mvn -B clean test

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
