language: java
jdk:
  - openjdk8

git:
  quiet: true

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.2.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb && sudo service elasticsearch restart
  - sudo chmod 777 .travis/hbase-init.sh

install: true

before_script:
  - sleep 10
  - .travis/hbase-init.sh

script:
  - mvn clean compile > /dev/null 2>&1
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Dsonar.projectKey=nimbo3_Keenbo

cache:
  directories:
    - $HOME/.m2
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "nimbo3-1"
    token:
      secure: ${SONAR_TOKEN}
